version: "3.4"

services:
  fxtractapi:
    image: fxtractapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - "mongo"
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - "mongo-data:/data/db"
    restart: always
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    depends_on:
      - "mongo"
    restart: always

volumes:
  mongo-data:
    driver: local
