version: "3.4"

services:
  fxtractapi:
    image: doubleu/fxtract-api
    # build:
    #   context: .
    #   dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    # volumes:
    #   - "fxtract-pdfs:/app/pdfs"
    restart: always
    depends_on:
      - mongo
      - rabbitmq
      - redis
      - fre-service
      - processing-plan-service
    networks:
      - fxtnet
    env_file:
      - .env

  fre-service:
    image: doubleu/fre-service
    restart: always
    networks:
      - fxtnet
    stdin_open: true
    tty: true
    environment:
      - AMQP=amqp://guest:guest@rabbitmq:5672

  processing-plan-service:
    image: doubleu/processing-plan-service
    restart: always
    networks:
      - fxtnet
    stdin_open: true
    tty: true
    environment:
      - AMQP=amqp://guest:guest@rabbitmq:5672"
      - REDIS="tcp://redis:6379"

  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - "mongo-data:/data/db"
    restart: always
    networks:
      - fxtnet

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    depends_on:
      - "mongo"
    restart: always
    networks:
      - fxtnet

  redis:
    image: redis
    ports:
      - 6379:6379
    restart: always
    networks:
      - fxtnet

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    restart: always
    networks:
      - fxtnet

volumes:
  mongo-data:
    driver: local

networks:
  fxtnet:
    driver: bridge
